config/routes.rb
App365Films::Application.routes.draw do

  devise_for :users

  root :to => "films#list"
  resources :films

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :films
end

app/models/director.rb
class Director < ActiveRecord::Base
  has_many :films
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :director
  belongs_to :category

  validates :title, presence: true
  validates :year, numericality: { only_integer: true }

  scope :planned, -> { where('planned_at IS NOT NULL') }
  scope :viewed, -> { where('seen_at IS NOT NULL') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, except: [:list, :new, :create]
  before_action :set_film, only: [:edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def list
    @films = Film.planned.all
  end

  def new
    @film = Film.new
  end

  def edit
  end

  # POST /films
  def create
    @film = Film.new(user_signed_in? ? film_params : recommandation_params)

    if @film.save
      redirect_to root_path, notice: t('films.added')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /films/1
  def update
    if @film.update(film_params)
      redirect_to edit_film_path(@film), notice: t('films.added')
    end
  end

  # DELETE /films/1
  def destroy
    @film.destroy
    redirect_to films_url, notice: t('films.failed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    def film_params
      params.require(:film).permit(:title,:description, :year, :recommended_by, :category_id, :director_id, :planned_at, :seen_at, :rate)
    end

    # Only allow a trusted parameter "white list" through.
    def recommandation_params
      params.require(:film).permit(:title,:description, :year, :recommended_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/recommandations_helper.rb
module RecommandationsHelper
end

app/views/films/_form.html.haml
= simple_form_for(@film) do |f|
  -if @film.errors.any?
    .alert.alert-danger
      %span
        = pluralize(@film.errors.count, t('activerecord.errors.found'))
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg

  =f.input :title, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :recommended_by, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :description, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :planned_at, as: :date, start_year: Date.today.year, end_year: Date.today.year + 1, order: [:day, :month, :year]
  =f.input :seen_at, as: :date, start_year: Date.today.year, end_year: Date.today.year + 1, order: [:day, :month, :year]
  =f.input :rate
  =f.input :category_id, collection: Category.all
  =f.input :director_id, collection: Director.all
  =f.input :year, input_html: { class: 'form-control', value: Date.today.year}, wrapper_html: { class: 'form-group' }, label: t('recommandations.year')


  .actions
    = f.button :submit, class: 'btn btn-success'

app/views/films/_recommandation_form.html.haml
= simple_form_for(@film) do |f|
  -if @film.errors.any?
    .alert.alert-danger
      %span
        = pluralize(@film.errors.count, t('activerecord.errors.found'))
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg

  =f.input :title, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :recommended_by, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :description, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }
  =f.input :year, input_html: { class: 'form-control', value: Time.now.year}, wrapper_html: { class: 'form-group' }, label: t('recommandations.year')
  .actions
    = f.button :submit, class: 'btn btn-success'

app/views/films/edit.html.haml
%h1
  = t('recommandations.edit')
= render 'form'
= link_to t('back'), films_path

app/views/films/index.html.haml
%h1 
  = t('recommandations.list')
%table.table
  %tr
    %th
      Film
    %th
      Année
    %th
      Actions
  -@films.each do |film|
    %tr
      %td
        =film.title
      %td
        =film.year
      %td
        = link_to t('actions.edit'), edit_film_path(film)
        = link_to t('actions.delete'), film, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New film', new_film_path

app/views/films/list.html.haml
%h1 
  = t('recommandations.list')
%table.table
  %tr
    %th
      Film
    %th
      Année
  -@films.each do |film|
    %tr
      %td
        =film.title
      %td
        =film.year

= link_to t('films.new'), new_film_path

app/views/films/new.html.haml
%h1= t 'recommandations.new'
-if user_signed_in?
  = render 'form'
  = link_to t('back'), films_path
- else
  = render 'recommandation_form'
  = link_to t('back'), root_path

app/views/layouts/_menu.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to root_path, {:class => 'navbar-brand'} do
        =t 'app_name'
      %button.navbar-toggle{:type => "button", 'data-toggle' => "collapse", 'data-target' => ".navbar-collapse"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li
            =link_to t('recommandations.list'), films_path
          %li
            =button_to t('devise.common.sign_out'), destroy_user_session_path, :method => 'delete', class: 'btn btn-light btn-menu'
        -else
          %li
            =link_to t('films.new'), new_film_path
          %li
            =link_to t('devise.common.sign_in'), new_user_session_path, class: 'btn btn-light btn-menu'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %title= content_for?(:title) ? yield(:title) : t('app_name')
    %meta{:charset => "utf-8"}
    %meta{:content => content_for?(:description) ? yield(:description) : t('app_name'), :name => "description"}
      = stylesheet_link_tag "application", :media => "all"
      = csrf_meta_tags
      = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'layouts/menu'
    .main.container
      = render 'layouts/messages'
      = yield
  %footer
    -unless @mentions.nil?
      =link_to t("switch_lang_#{lang_switch}"), root_path(:locale => lang_switch)
      |
      =link_to t('pages.mentions'), '#myModal', 'data-toggle' => 'modal' 
      #myModal.modal.fade{'tabindex'=>"-1", :role => "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true"}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{:type => "button", 'data-dismiss' => "modal", 'aria-hidden' => "true"}
                &times;
              %h4.modal-title= t('pages.mentions')
            .modal-body
              %h4=@mentions.title
              =raw @mentions.content
            .modal-footer
              %button.btn.btn-success{:type => "button", 'data-dismiss' => "modal"}
                =t('close')


    = javascript_include_tag "application"
    / ! end of .container
  / ! end of #main